### ISSUE TITLE
Idee für "Entscheidungsdiagramme"

### ISSUE THREAD

**Issue by ptrjst** [hema-ltv1927/hema-ltv1927.github.io#1]
Hi @LWalloscheck - Evtl. können wir mit 'Mermaid' auch auf einfache Weise die Entscheidungsdiagramme visualisieren.
Siehe hier: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams
Gruß,
@ptrjst

**Comment by LWalloscheck** [comment]
@ptrjst ja das könnte klappen
Soll ich das Plugin mal einbauen?

**Comment by ptrjst** [comment]
Ich denke, wenn man sich an die Syntax hält, macht das GitHub beim erstellen der Seite automatisch ...

**Comment by LWalloscheck** [comment]
mermaid JS Library ist mit Hilfe eines Includes "mermaid.html" eingebunden.
Kleine Modifikation erforderlich, da jekyll ein "code" Knoten mit class="language-mermaid" erzeugt.
Die JS Lib aber im Default nach der class="mermaid" sucht
